# Generated by Django 5.2.4 on 2025-07-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/')),
                ('body_part', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('scan_date', models.DateField()),
                ('institution', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
